# The docker-compose DSL syntax format we're using.
version: "2.1"

# The containers we want to start and the images to start them from.
services:

  # Our basic node server we'll name "basic".
  basic: 
    # The directory path - relative to this compose file - where
    # we'll be able to find the Dockerfile.
    build: ./
    # The port mappings we do so that traffic that docker
    # will forward from localhost -> container.
    ports:
      - "44444:8080"
